### PR TITLE
fix: home page user stream

### PR DESCRIPTION
**Pull request by tnc1997**
I have taken a look over the home page and made a couple of changes which hopefully fix the issue that you are experiencing with the '+' option not appearing correctly. I have tested these changes by navigating directly to the home page when the application starts and creating a mock stream that periodically emits a user with a different profile type. Please note however that I have not tested these changes using your Firebase Auth so let me know if you experience any issues running the application.

### CODE REVIEW

**Comment by sumitt1080** [comment]
I tested after merging, after creating a new account, it throws a error screen which i attached below. But that error screen get fixed after a hot reload. However, this is not the case if i login a existing user.
Webp net-compress-image



https://user-images.githubusercontent.com/51052011/104326334-a40b3380-550f-11eb-86bb-dbb1d615cd39.mp4

**Comment by tnc1997** [comment]
@sumitt1080 apologies that it didn't work using your Flutter Auth is there any chance that you might be able to attach the full stack trace from the terminal in order for me to get a better idea of where in the code the error is being thrown?

After taking a closer look at the rest of the application I have had a thought as to what the problem could be. If the user is logging into an account that already exists, then the [`_submitAuthForm`](https://github.com/sumitt1080/Nuget/blob/dc4c9ad3048ef2a9cf521c7674ee52754a595f4f/lib/pages/auth_screen.dart#L38-L41) method simply signs the user into the application, however if the user is creating a new account, then the [`_submitAuthForm`](https://github.com/sumitt1080/Nuget/blob/dc4c9ad3048ef2a9cf521c7674ee52754a595f4f/lib/pages/auth_screen.dart#L43-L67) method first creates the user in Firebase Auth and then creates the user in Firebase Firestore. In the second scenario, as soon as the user is created in Firebase Auth, the [`MyApp`](https://github.com/sumitt1080/Nuget/blob/dc4c9ad3048ef2a9cf521c7674ee52754a595f4f/lib/main.dart#L42-L47) widget will navigate to the [`MyHomePage`](https://github.com/sumitt1080/Nuget/blob/dc4c9ad3048ef2a9cf521c7674ee52754a595f4f/lib/pages/home.dart#L180-L192) widget, which will then attempt to get the user from Firebase Firestore. If the user does not yet exist in Firebase Firestore at that point in time, then it could be causing the stream's data to be null instead of a user. This would support the fact that hot reloading the application fixes the error, because in theory the `authStateChanges` stream emits when the user is created and not again until the application is hot reloaded, by which time the user has likely been created in Firebase Firestore.

**Comment by sumitt1080** [comment]
This is the issue which is not getting fixed, i tried some tweaks but all in vain. Please find the stackTrace pic below. 
Let's see if we can fix this issue.
Exception

is there a way that i can store user first in firestore , then create it in firebaseauth, because i rearranged the code to achieve this, but it didn't worked.

**Comment by tnc1997** [comment]
I've [refactored](https://github.com/tnc1997/flutter-nuget/tree/refactor-home-page) the [`asyncMap`](https://api.dart.dev/stable/2.10.4/dart-async/Stream/asyncMap.html) to [`switchMap`](https://pub.dev/documentation/rxdart/latest/rx/SwitchMapExtension/switchMap.html) would you be able to give it a try and let me know if it works any better? In theory the [`switchMap`](https://pub.dev/documentation/rxdart/latest/rx/SwitchMapExtension/switchMap.html) means that it will listen for changes to the user in Firebase Firestore rather than just getting the user once.

**Comment by sumitt1080** [comment]
Okay, will let u know soon

**Comment by sumitt1080** [comment]
@tnc1997 it worked 😃. Thank u so much for help. Please have a look.

https://user-images.githubusercontent.com/51052011/104469668-c3bd5d00-55de-11eb-9812-b340470948e5.mp4


Can i contact u again if i find some new major issue?

**Comment by tnc1997** [comment]
> Can i contact u again if i find some new major issue?

Of course please feel free to get in touch with me if there's anything that I can do to help in the future!

**Pull request merged**
